modLoader = "javafml"
loaderVersion = "[35,)"
license = "MIT"

[[mods]]
modId = "cryonicconfig"
version = "${version}"
displayName = "Cryonic Config"
authors = "Slainlight"
description = '''
Chill Minimal Config API
'''

[[dependencies.cryonicconfig]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cryonicconfig]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"
