modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/matthewperiut/cryonicconfig/issues"
license = "MIT"

[[mods]]
modId = "cryonicconfig"
version = "${version}"
displayName = "Cryonic Config"
authors = "Slainlight"
description = '''
Chill Minimal Config API
'''
logoFile = "assets/cryonicconfig/logo.png"

[[dependencies.cryonicconfig]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cryonicconfig]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.4]"
ordering = "NONE"
side = "BOTH"
