modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/matthewperiut/cryonic_config/issues"
license = "MIT"

[[mods]]
modId = "cryonic_config"
version = "${version}"
displayName = "Cryonic Config"
authors = "Slainlight"
description = '''
Chill Minimal Config API
'''
logoFile = "assets/cryonic_config/logo.png"

[[dependencies.cryonic_config]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies.cryonic_config]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.5]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cryonic_config.mixins.json"
